model_selection module: Group splitter
basf/MolPipeline pull request #74
Opened 2024-08-27 20:50 UTC by JochenSiegWork

Add the sklearn GroupShuffleSplit class, which optionally can create splits based on the size of the groups, i.e. the number of samples instead of the number of groups.

This PR makes the splitter available as experimental feature in MolPipeline. However, if it's accepted and merged into sklearn we can remove this PR (or experimental feature) from MolPipeline. See the sklearn PR https://github.com/scikit-learn/scikit-learn/pull/29683

2025-04-11 10:45 UTC, c-w-feldmann requested changes

2025-04-11 10:45 UTC, c-w-feldmann commented on molpipeline/experimental/model_selection/splitter.py
> +        class_indices = np.arange(len(classes))
Also make it realted to the counts. Maybe, `unique_groups` and `unique_group_sizes`

2025-04-11 10:45 UTC, c-w-feldmann commented on molpipeline/experimental/model_selection/splitter.py
> +            for class_index, group_size, bucket_index in zip(
This for  loop is a bit hard to understand.
Maybe create a list of name tuples over which you iterate:
```
GroupInfo = NamedTuple("GroupInfo", ["index", "size", "random_assignment"])
```

2025-04-11 10:45 UTC, c-w-feldmann commented on tests/test_experimental/test_model_selection/test_splitter.py
> +                    GroupShuffleSplit(
maybe something like this?
```python
split_generator = GroupShuffleSplit(
    train_size=train_size, split_size=split_size
).split(X, y, groups)
X_train, X_test = next(split_generator)  # pylint: disable=invalid-name
```

2025-04-11 10:45 UTC, c-w-feldmann commented on tests/test_experimental/test_model_selection/test_splitter.py
> +    def test_invalid_split_size(self) -> None:
Also test if an error ist raised during split when the variable is changed after initialization

2025-04-11 13:03 UTC, JochenSiegWork commented on molpipeline/experimental/model_selection/splitter.py
> +        split_size: SplitSizeOption = "groups",
I aggree and went with `split_mode`

2025-04-11 13:05 UTC, JochenSiegWork commented on molpipeline/experimental/model_selection/splitter.py
> +            samples_sizes = np.array([n_train, n_test], dtype=np.int_)
Done

2025-04-11 13:10 UTC, JochenSiegWork commented on molpipeline/experimental/model_selection/splitter.py
> +        class_indices = np.arange(len(classes))
I tried to stay close to the names that are used internally in sklearn splitter functions but your right. Is it better now?

2025-04-11 13:12 UTC, JochenSiegWork commented on tests/test_experimental/test_model_selection/test_splitter.py
> +                    GroupShuffleSplit(
done

2025-04-11 13:18 UTC, JochenSiegWork commented on tests/test_experimental/test_model_selection/test_splitter.py
> +    def test_invalid_split_size(self) -> None:
done

2025-04-14 13:18 UTC, c-w-feldmann commented on molpipeline/experimental/model_selection/splitter.py
> +                random_bucket_assignments,  # the random bucket assignments
> random_bucket_assignments,  # the random bucket assignments
I think you can delete this :D
How about:
```
for i, group_index in enumerate(unique_groups_indices_shuffled):
    group_size = group_counts_shuffled[i]
    assigned_bucket_ = random_bucket_assignments[i]

2025-04-14 13:29 UTC, JochenSiegWork commented on molpipeline/experimental/model_selection/splitter.py
> +                random_bucket_assignments,  # the random bucket assignments
done

2025-04-14 14:50 UTC, c-w-feldmann approved these changes

2025-04-14 14:51 UTC, merged